package com.mshdabiola.designsystem.theme.util

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF914278)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8EC)
val md_theme_light_onPrimaryContainer = Color(0xFF3B002E)
val md_theme_light_secondary = Color(0xFF705765)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBD9EA)
val md_theme_light_onSecondaryContainer = Color(0xFF281621)
val md_theme_light_tertiary = Color(0xFF80543E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCC)
val md_theme_light_onTertiaryContainer = Color(0xFF311303)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFF0DEE5)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4449)
val md_theme_light_outline = Color(0xFF81737A)
val md_theme_light_inverseOnSurface = Color(0xFFF9EEF1)
val md_theme_light_inverseSurface = Color(0xFF342F31)
val md_theme_light_inversePrimary = Color(0xFFFFADDF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF914278)
val md_theme_light_outlineVariant = Color(0xFFD3C2C9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFADDF)
val md_theme_dark_onPrimary = Color(0xFF591147)
val md_theme_dark_primaryContainer = Color(0xFF752A5F)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8EC)
val md_theme_dark_secondary = Color(0xFFDEBECE)
val md_theme_dark_onSecondary = Color(0xFF3F2A37)
val md_theme_dark_secondaryContainer = Color(0xFF57404D)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBD9EA)
val md_theme_dark_tertiary = Color(0xFFF4BA9F)
val md_theme_dark_onTertiary = Color(0xFF4B2715)
val md_theme_dark_tertiaryContainer = Color(0xFF653D29)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFEAE0E3)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFEAE0E3)
val md_theme_dark_surfaceVariant = Color(0xFF4F4449)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C2C9)
val md_theme_dark_outline = Color(0xFF9C8D94)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1D)
val md_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val md_theme_dark_inversePrimary = Color(0xFF914278)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFADDF)
val md_theme_dark_outlineVariant = Color(0xFF4F4449)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF914278)
val corrent = Color(0xFF3AC200)
val light_corrent = Color(0xFF1D6D00)
val light_oncorrent = Color(0xFFFFFFFF)
val light_correntContainer = Color(0xFF7BFF50)
val light_oncorrentContainer = Color(0xFF042100)
val dark_corrent = Color(0xFF5CE230)
val dark_oncorrent = Color(0xFF0B3900)
val dark_correntContainer = Color(0xFF145200)
val dark_oncorrentContainer = Color(0xFF7BFF50)