name: Release all on github


on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  BuildBinaries:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, osx-x64, win-x64, android ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            build: packageReleaseUberJarForCurrentOS packageDeb

          - runtime: osx-x64
            os: macOS-latest
            build: packageUberJarForCurrentOS packageDmg

          - runtime: win-x64
            os: windows-latest
            build: packageReleaseUberJarForCurrentOS packageReleaseMsi

          - runtime: android
            os: ubuntu-latest
            build: assembleRelease

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        if: ${{ matrix.runtime != 'linux-fedora-x64' }}
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        if: ${{ matrix.runtime == 'android' }}

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
        if: ${{ matrix.runtime == 'android' }}

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
        if: ${{ matrix.runtime == 'android' }}

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: >
            ${{ matrix.build }}
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        if: ${{ matrix.runtime == 'android' }}
        with:
          releaseDirectory: composeApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Create destination directory
        if: ${{ matrix.runtime == 'android' }}
        run: mkdir -p binaries/main

      - name: Move directory release
        if: ${{ matrix.runtime == 'android' }}
        run: mv composeApp/build/outputs/apk/release binaries/main/release

      - name: Move directory mapping
        if: ${{ matrix.runtime == 'android' }}
        run: mv composeApp/build/outputs/mapping binaries/main/mapping

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-package-${{ matrix.runtime }}
          path: |
            binaries/main/*/
            composeApp/build/compose/binaries/main/*/
            composeApp/build/compose/binaries/main-release/*/
            composeApp/build/compose/jars/
            !composeApp/build/compose/binaries/main/app/
            ${{ env.SIGNED_RELEASE_FILE }}
        # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            composeApp/build/compose/logs/
  ReleaseBinaries:
    name: Make a release
    needs: [ BuildBinaries ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
      - name: list
        run: find . -type f

      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "*/binaries/**/**/*,*/composeApp/build/compose/binaries/**/**/*,*/composeApp/build/compose/binaries/main-release/*/*.*,*/composeApp/build/compose/jars/*.jar"
          draft: true
          token: ${{ secrets.TOKEN }}

